### ISSUE TITLE
Plugin does not work with Android Studio 2.0

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-gradle-android#4]
AS 2.0 was just released, and features a thing called ["instant run"](http://tools.android.com/tech-docs/instant-run) which is enabled by default, and gives an error during the build:

```
Error:Execution failed for task ':app:compileDebugCeylonWithCeylonc'.
> Could not find property 'consumedInputStreams' on task ':app:incrementalDebugSupportDex'.
```

Disabling the feature solves the problem, but it might be interesting to make ceylon-gradle-android compatible with this?

**Comment by FroMage** [comment]
I fixed that.
